var _yt_www={};(function(g){var window=this;var baa,caa,ra,Ca,Ga,eb,kaa,fb,gb,hb,ib,nb,laa,ob,maa,naa,vb,Hb,Xb,dc,fc,Kc,yaa,zaa,xaa,nd,od,ud,wd,Caa,Bd,Fd,zd,xd,Eaa,Ed,Cd,Dd,Hd,Daa,Md,Faa,Gaa,ge,Iaa,qe,xe,we,Kaa,Laa,ye,ze,Be,Naa,Fe,Le,Ke,Ge,Pe,Saa,Te,Qe,Re,Raa,We,Ve,Ye,Je,De,Ce,Ee,Ze,Ne,Xe,Oe,af,Uaa,Qaa,Waa,kf,nf,qf,sf,yf,zf,Rf,Sf,aba,$f,ag,bba,dg,hg,fg,eg,cba,jg,kg,lg,og,qg,rg,sg,vg,ug,xg,tg,yg,mg,pg,iba,zg,Ag,jba,kba,Gg,Ig,Kg,mba,Rg,Sg,Vg,Tg,nba,bh,ih,hh,oba,lh,uba,tba,sba,rh,rba,pba,qba,vba,zh,xh,Ah,Ch,wba,xba,Dh,Eh,Jh,Nh,Oh,Ph,Sh,Th,Uh,
Dba,Eba,Kh,Mh,Ih,Cba,Lh,Gba,Hba,Iba,ai,bi,pa,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.p=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.ga=function(a){a.getInstance=function(){return a.uc?a.uc:a.uc=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ja=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ka=function(a){return"string"==typeof a};
g.la=function(a){return"number"==typeof a};
g.ma=function(a){return"function"==g.ha(a)};
g.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.q=function(a,b,c){g.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.q.apply(null,arguments)};
g.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.t=function(a,b){function c(){}
c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.eV=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
ra=function(a){ra[" "](a);return a};
g.sa=function(a,b){try{return ra(a[b]),!0}catch(c){}return!1};
g.ta=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.ta);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.ua=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return/^[\s\xa0]*$/.test(a)};
g.wa=function(a){return(0,window.encodeURIComponent)(String(a))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Aa=function(a){return null==a?"":String(a)};
g.Da=function(a,b){for(var c=0,d=(0,g.Ba)(String(a)).split("."),e=(0,g.Ba)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var l=d[k]||"",n=e[k]||"",u=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var I=u.exec(l)||["","",""],U=w.exec(n)||["","",""];if(0==I[0].length&&0==U[0].length)break;c=Ca(0==I[1].length?0:(0,window.parseInt)(I[1],10),0==U[1].length?0:(0,window.parseInt)(U[1],10))||Ca(0==I[2].length,0==U[2].length)||Ca(I[2],U[2])}while(0==c)}return c};
Ca=function(a,b){return a<b?-1:a>b?1:0};
g.Fa=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
Ga=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Ha=function(a){var b=g.ka(void 0)?g.za(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ja=function(a,b,c){b=g.Ia(a,b,c);return 0>b?null:g.ka(a)?a.charAt(b):a[b]};
g.Ia=function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.La=function(a,b){return 0<=(0,g.Ka)(a,b)};
g.Oa=function(a,b){var c=(0,g.Ka)(a,b),d;(d=0<=c)&&g.Ma(a,c);return d};
g.Ma=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Pa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Qa=function(a){return function(){return a}};
g.Ra=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Sa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Ta=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ua=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Va=function(a){for(var b in a)return!1;return!0};
g.Wa=function(a,b){b in a&&delete a[b]};
g.Xa=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ya=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.$a=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.bb=function(a){return g.ya(g.ab,a)};
g.cb=function(){return g.bb("Trident")||g.bb("MSIE")};
g.db=function(){return(g.bb("Chrome")||g.bb("CriOS"))&&!g.bb("Edge")};
eb=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.bb("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.cb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.Fp;c.Fp=null;a()}};
return function(a){d.next={Fp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
fb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
gb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
hb=function(){this.C=this.A=null};
ib=function(){this.next=this.scope=this.pe=null};
nb=function(a,b){jb||laa();kb||(jb(),kb=!0);var c=lb,d=mb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);jb=function(){a.then(ob)}}else jb=function(){var a=ob;
!g.ma(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.bb("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(pb||(pb=kaa()),pb(a)):g.da.setImmediate(a)}};
ob=function(){for(var a;a=lb.remove();){try{a.pe.call(a.scope)}catch(b){eb(b)}gb(mb,a)}kb=!1};
g.qb=function(){this.Md=this.Md;this.Kb=this.Kb};
g.tb=function(a,b){g.rb(a,g.r(g.sb,b))};
g.rb=function(a,b){a.Md?g.ca(void 0)?b.call(void 0):b():(a.Kb||(a.Kb=[]),a.Kb.push(g.ca(void 0)?(0,g.q)(b,void 0):b))};
g.sb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.ub=function(a){g.qb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.sd={};this.F=!!a};
maa=function(a,b,c){nb(function(){a.apply(b,c)})};
g.xb=function(a){vb(g.wb,arguments)};
g.v=function(a,b){return a in g.wb?g.wb[a]:b};
g.zb=function(a,b){g.ma(a)&&(a=g.yb(a));return window.setTimeout(a,b)};
g.Ab=function(a,b){g.ma(a)&&(a=g.yb(a));return window.setInterval(a,b)};
g.Bb=function(a){window.clearTimeout(a)};
g.Cb=function(a){window.clearInterval(a)};
g.yb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Db(b),b;}}:a};
g.Db=function(a,b,c,d,e){var f=g.p("yt.logging.errors.log");f?f(a,b,c,d,e):(f=g.v("ERRORS",[]),f.push([a,b,c,d,e]),g.xb("ERRORS",f))};
naa=function(a,b,c,d,e){var f=!1;if(g.wb.Qo&&g.wb.Qo.log_window_onerror_fraction&&Math.random()<g.wb.Qo.log_window_onerror_fraction)f=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,n=k.length;l<n;l++)if(0<k[l].src.indexOf("/debug-")){f=!0;break}f&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Db(e))};
g.Fb=function(a){return a in g.Eb};
g.Gb=function(a,b,c){var d=b||{};if(a=a in g.Eb?g.Eb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
vb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.x=function(a,b,c){var d=Hb();if(d){var e=d.subscribe(a,function(){if(!Ib||Ib!=e){var d=arguments,k;k=function(){Jb[e]&&b.apply(c||window,d)};
try{Kb[a]?k():g.zb(k,0)}catch(l){g.Db(l)}}},c);
Jb[e]=!0;Lb[a]||(Lb[a]=[]);Lb[a].push(e);return e}return 0};
g.Mb=function(a){var b=Hb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.y)(a,function(a){b.unsubscribeByKey(a);delete Jb[a]}))};
g.z=function(a,b){var c=Hb();return c?c.publish.apply(c,arguments):!1};
g.Nb=function(a,b){Kb[a]=!0;var c=Hb(),c=c?c.publish.apply(c,arguments):!1;Kb[a]=!1;return c};
Hb=function(){return g.p("yt.pubsub.instance_")};
g.Ob=function(){return!!g.p("yt.scheduler.instance")};
g.Pb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.p("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.zb(a,b||0)};
g.Qb=function(a,b){return g.Pb(a,b)};
g.Rb=function(a){if(!(0,window.isNaN)(a)){var b=g.p("yt.scheduler.instance.cancelJob");b?b(a):g.Bb(a)}};
g.Tb=function(a){for(var b=0,c=a.length;b<c;b++)g.Rb(a[b])};
g.Ub=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.H=d?g.yb(d):null;this.F=e?g.yb(e):null;this.D=[];this.A=this.C=0};
g.Vb=function(a){g.Rb(a.C);a.C=g.Qb((0,g.q)(a.init,a))};
g.Yb=function(a){a.name in Wb&&Xb(a.name);Wb[a.name]={reqs:[],disable:(0,g.q)(a.disable,a)};(0,g.y)(a.deps,function(b){if(!(b in Wb))throw Error("Module "+b+" required by "+a.name);Wb[b].reqs.push(a.name)});
a.enable()};
Xb=function(a){if(a in Wb){var b=Wb[a];(0,g.y)(b.reqs,function(a){Xb(a)});
try{b.disable()}catch(c){}delete Wb[a]}};
g.ac=function(){this.A="";this.C=$b};
g.bc=function(a){return a instanceof g.ac&&a.constructor===g.ac&&a.C===$b?a.A:"type_error:Const"};
dc=function(){this.A="";this.C=cc};
g.ec=function(a){if(a instanceof dc&&a.constructor===dc&&a.C===cc)return a.A;g.ha(a);return"type_error:SafeStyle"};
fc=function(a){var b=new dc;b.A=a;return b};
g.gc=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof g.ac)d=g.bc(d);else if(oaa.test(d)){for(var e=!0,f=!0,k=0;k<d.length;k++){var l=d.charAt(k);"'"==l&&f?e=!e:'"'==l&&e&&(f=!f)}e&&f||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?fc(b):paa};
g.ic=function(){this.A="";this.C=hc};
g.jc=function(a){if(a instanceof g.ic&&a.constructor===g.ic&&a.C===hc)return a.A;g.ha(a);return"type_error:SafeUrl"};
g.lc=function(a){if(a instanceof g.ic)return a;a=a.Sf?a.Qe():String(a);qaa.test(a)||(a="about:invalid#zClosurez");return g.kc(a)};
g.kc=function(a){var b=new g.ic;b.A=a;return b};
g.nc=function(){this.A="";this.C=mc};
g.oc=function(a){if(a instanceof g.nc&&a.constructor===g.nc&&a.C===mc)return a.A;g.ha(a);return"type_error:TrustedResourceUrl"};
g.qc=function(){this.A="";this.B=pc;this.C=null};
g.rc=function(a){if(a instanceof g.qc&&a.constructor===g.qc&&a.B===pc)return a.A;g.ha(a);return"type_error:SafeHtml"};
g.tc=function(a){if(a instanceof g.qc)return a;var b=null;a.um&&(b=a.Cg());a=g.xa(a.Sf?a.Qe():String(a));return g.sc(a,b)};
g.wc=function(a,b,c){if(!uc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in raa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.vc(a,b,c)};
g.xc=function(a){function b(a){g.ia(a)?(0,g.y)(a,b):(a=g.tc(a),d+=g.rc(a),a=a.Cg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.y)(arguments,b);return g.sc(d,c)};
g.sc=function(a,b){var c=new g.qc;c.A=a;c.C=b;return c};
g.vc=function(a,b,c){var d=null,e,f="";if(b)for(e in b){if(!uc.test(e))throw Error('Invalid attribute name "'+e+'".');var k=b[e];if(null!=k){var l,n=a;l=e;if(k instanceof g.ac)k=g.bc(k);else if("style"==l.toLowerCase()){if(!g.na(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof dc||(k=g.gc(k));k=g.ec(k)}else{if(/^on/i.test(l))throw Error('Attribute "'+l+'" requires goog.string.Const value, "'+k+'" given.');if(l.toLowerCase()in
saa)if(k instanceof g.nc)k=g.oc(k);else if(k instanceof g.ic)k=g.jc(k);else if(g.ka(k))k=g.lc(k).Qe();else throw Error('Attribute "'+l+'" on tag "'+n+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Sf&&(k=k.Qe());l=l+'="'+g.xa(String(k))+'"';f+=" "+l}}e="<"+a+f;null!=c?g.ia(c)||(c=[c]):c=[];!0===taa[a.toLowerCase()]?e+=">":(d=g.xc(c),e+=">"+g.rc(d)+"</"+a+">",d=d.Cg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.sc(e,d)};
g.yc=function(a,b){a.innerHTML=g.rc(b)};
g.zc=function(a,b){var c;c=b instanceof g.ic?b:g.lc(b);a.href=g.jc(c)};
g.A=function(a,b){return a?a.dataset?a.dataset[g.Ac(b)]:a.getAttribute("data-"+b):null};
g.Ac=function(a){return Bc[a]||(Bc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Dc=function(a,b){var c=g.Cc(a);window.spf.script.load(a,c,b)};
g.Cc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(uaa,""),b=b.replace(vaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Ec=function(a){if(a.classList)return a.classList;a=a.className;return g.ka(a)&&a.match(/\S+/g)||[]};
g.B=function(a,b){return a.classList?a.classList.contains(b):g.La(g.Ec(a),b)};
g.C=function(a,b){a.classList?a.classList.add(b):g.B(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.D=function(a,b){a.classList?a.classList.remove(b):g.B(a,b)&&(a.className=(0,g.Fc)(g.Ec(a),function(a){return a!=b}).join(" "))};
g.Gc=function(a,b,c){c?g.C(a,b):g.D(a,b)};
g.Hc=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.Ic=function(a,b){this.width=a;this.height=b};
g.Jc=function(){return g.bb("iPhone")&&!g.bb("iPod")&&!g.bb("iPad")};
Kc=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Nc=function(a){return Lc[a]||(Lc[a]=0<=g.Da(g.Mc,a))};
g.Pc=function(a){return Number(g.Oc)>=a};
g.E=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.Qc=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.Sc=function(a,b){g.Sa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Rc.hasOwnProperty(d)?a.setAttribute(Rc[d],b):g.ua(d,"aria-")||g.ua(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Uc=function(a){return g.Tc(a||window)};
g.Tc=function(a){a=a.document;a=g.Vc(a)?a.documentElement:a.body;return new g.Ic(a.clientWidth,a.clientHeight)};
g.Xc=function(a){var b=g.Wc(a);a=a.parentWindow||a.defaultView;return g.F&&g.Nc("10")&&a.pageYOffset!=b.scrollTop?new g.Hc(b.scrollLeft,b.scrollTop):new g.Hc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Wc=function(a){return a.scrollingElement?a.scrollingElement:!g.Yc&&g.Vc(a)?a.documentElement:a.body||a.documentElement};
g.$c=function(a,b,c){return g.Zc(window.document,arguments)};
g.Zc=function(a,b){var c=String(b[0]),d=b[1];if(!waa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.$a(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ka(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.Sc(c,d));2<b.length&&g.ad(a,c,b,2);return c};
g.ad=function(a,b,c,d){function e(c){c&&b.appendChild(g.ka(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ja(f)||g.na(f)&&0<f.nodeType?e(f):(0,g.y)(xaa(f)?g.Pa(f):f,e)}};
g.Vc=function(a){return"CSS1Compat"==a.compatMode};
g.bd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.cd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.dd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
yaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
zaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.ed=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
xaa=function(a){if(a&&"number"==typeof a.length){if(g.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.ma(a))return"function"==typeof a.item}return!1};
g.fd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.hd=function(a){var b=a.__yt_uid_key;b||(b=gd(),a.__yt_uid_key=b);return b};
g.id=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.y)(a.childNodes,function(a){b.appendChild(g.id(a))}):b.innerHTML=a.innerHTML;
return b};
g.jd=function(){var a=window.document;if("visibilityState"in a)return a.visibilityState;var b=Aaa+"VisibilityState";if(b in a)return a[b]};
g.kd=function(a){return g.v("EXPERIMENT_FLAGS",{})[a]};
g.md=function(a,b){return(new g.ld(b)).Sb(a)};
g.ld=function(a){this.A=a};
nd=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(g.ia(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],nd(a,a.A?a.A.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),od(d,c),c.push(":"),nd(a,a.A?a.A.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":od(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}};
od=function(a,b){b.push('"',a.replace(Baa,function(a){var b=pd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),pd[a]=b);return b}),'"')};
g.qd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.rd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.td=function(a,b){this.A=0;this.K=void 0;this.D=this.C=this.B=null;this.F=this.H=!1;if(a!=g.fa)try{var c=this;a.call(b,function(a){g.sd(c,2,a)},function(a){g.sd(c,3,a)})}catch(d){g.sd(this,3,d)}};
ud=function(){this.next=this.context=this.C=this.B=this.A=null;this.D=!1};
wd=function(a,b,c){var d=vd.get();d.B=a;d.C=b;d.context=c;return d};
Caa=function(a,b,c){xd(a,b,c,null)||nb(g.r(b,a))};
g.yd=function(a){return new g.td(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],Caa(n,g.r(f,l),k);
else b(e)})};
g.Ad=function(a,b){zd(a,null,b,void 0)};
Bd=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,f=null,k=c.C;k&&(k.D||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(f=k);e&&(0==c.A&&1==d?Bd(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):Cd(c),Dd(c,e,3,b)))}a.B=null}else g.sd(a,3,b)};
Fd=function(a,b){a.C||2!=a.A&&3!=a.A||Ed(a);a.D?a.D.next=b:a.C=b;a.D=b};
zd=function(a,b,c,d){var e=wd(null,null,null);e.A=new g.td(function(a,k){e.B=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.ca(e)&&b instanceof g.Gd?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;Fd(a,e);return e.A};
g.sd=function(a,b,c){0==a.A&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,xd(c,a.R,a.Y,a)||(a.K=c,a.A=b,a.B=null,Ed(a),3!=b||c instanceof g.Gd||Daa(a,c)))};
xd=function(a,b,c,d){if(a instanceof g.td)return Fd(a,wd(b||g.fa,c||null,d)),!0;if(g.rd(a))return a.then(b,c,d),!0;if(g.na(a))try{var e=a.then;if(g.ma(e))return Eaa(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
Eaa=function(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,f)}catch(n){f(n)}};
Ed=function(a){a.H||(a.H=!0,nb(a.G,a))};
Cd=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
Dd=function(a,b,c,d){if(3==c&&b.C&&!b.D)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,Hd(b,c,d);else try{b.D?b.B.call(b.context):Hd(b,c,d)}catch(e){Id.call(null,e)}gb(vd,b)};
Hd=function(a,b,c){2==b?a.B.call(a.context,c):a.C&&a.C.call(a.context,c)};
Daa=function(a,b){a.F=!0;nb(function(){a.F&&Id.call(null,b)})};
g.Gd=function(a){g.ta.call(this,a)};
g.Jd=function(){return{apiaryHost:g.v("APIARY_HOST",void 0),op:g.v("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.v("GAPI_HINT_OVERRIDE"),gapiHintParams:g.v("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.v("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.v("INNERTUBE_API_VERSION",void 0),TD:g.v("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.v("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),VD:g.v("INNERTUBE_CONTEXT_HL",void 0),UD:g.v("INNERTUBE_CONTEXT_GL",void 0),LV:g.v("XHR_APIARY_HOST",
void 0)}};
g.Kd=function(a){a={client:{hl:a.VD,gl:a.UD,clientName:a.TD,clientVersion:a.innertubeContextClientVersion}};g.v("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.v("DELEGATED_SESSION_ID")});return a};
Md=function(){this.A=g.Jd();Ld||(Ld=Faa(this.A))};
Faa=function(a){return(new g.td(function(b){g.Dc(g.v("GAPI_LOADER_URL",void 0),function(){try{g.p("yt.gapi.load")("client",{gapiHintOverride:a.gapiHintOverride,_c:{jsl:{h:a.gapiHintParams}},callback:b})}catch(c){g.Db(c)}})})).then(function(){})};
Gaa=function(a,b,c,d){var e={path:"/youtubei/"+a.A.innertubeApiVersion+"/"+b,headers:{"X-Goog-Visitor-Id":g.v("VISITOR_DATA")},method:"POST",body:g.md(c)},f=(0,g.q)(a.D,a);Ld.then(function(){f();g.p("gapi.client.request")(e).execute(d||g.fa)})};
g.Nd=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.Sd=function(a,b){g.Od[a.endpoint]=g.Od[a.endpoint]||[];var c=g.Od[a.endpoint];c.push(a.Cb);Pd[a.endpoint]=b;20<=c.length?g.Qd():g.Rd()};
g.Qd=function(){g.Bb(g.Td);if(!g.Va(g.Od)){for(var a in g.Od){var b=g.Ud[a];if(!b){b=Pd[a];if(!b)continue;b=new b;g.Ud[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.Vd)());c[Haa[a]]=g.Od[a];b.B(a,c,{});delete g.Od[a]}g.Va(g.Od)||g.Rd()}};
g.Rd=function(){g.Bb(g.Td);g.Td=g.zb(g.Qd,g.v("VISIBILITY_TIMEOUT",1E4))};
g.Wd=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.Vd)());e[a]=b;g.Sd({endpoint:"log_event",Cb:e},c)};
g.Xd=function(){var a=g.v("client-screen-nonce",void 0);a||(a=g.v("EVENT_ID",void 0));return a};
g.Yd=function(a,b,c,d,e,f,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);f&&(l+="?"+f);k&&(l+="#"+k);return l};
g.Zd=function(a){return a?(0,window.decodeURI)(a):a};
g.ae=function(a,b){return b.match(g.$d)[a]||null};
g.be=function(a){return g.Zd(g.ae(3,a))};
g.ce=function(a){a=a.match(g.$d);return g.Yd(null,null,null,null,a[5],a[6],a[7])};
g.de=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.ee=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.fe=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.fe(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.wa(b))};
ge=function(a,b){for(var c in b)g.fe(c,b[c],a);return a};
g.he=function(a){a=ge([],a);a[0]="";return a.join("")};
g.ie=function(a,b){return g.ee(ge([a],b))};
g.je=function(a,b,c){a&&(c&&(c=g.ab,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.$c("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.ed(a).body.appendChild(a)):Iaa(a,b))};
g.ke=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.je(a,void 0)}catch(b){g.je(a,void 0)}};
Iaa=function(a,b){var c=new window.Image,d=""+Jaa++;le[d]=c;c.onload=c.onerror=function(){b&&le[d]&&b();delete le[d]};
c.src=a};
g.me=function(a,b){this.version=a;this.args=b};
g.ne=function(a,b){this.topic=a;this.yf=b};
g.pe=function(a,b){var c=g.oe();return c?c.publish.call(c,a.toString(),a,b):!1};
g.oe=function(){return g.p("yt.pubsub2.instance_")};
qe=function(a){g.me.call(this,1,arguments)};
g.re=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.se=function(a,b){return a&&b?b instanceof g.re?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.te=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.ue=function(a,b){var c=Math.max(a.left,b.left),d=Math.min(a.left+a.width,b.left+b.width);if(c<=d){var e=Math.max(a.top,b.top),f=Math.min(a.top+a.height,b.top+b.height);if(e<=f)return a.left=c,a.top=e,a.width=d-c,a.height=f-e,!0}return!1};
g.ve=function(a){return new g.Ic(a.width,a.height)};
xe=function(a){this.A=a||window;this.R=this.B=0;if(this.A.performance&&this.A.performance.timing&&this.A.performance.getEntriesByType){a=g.Uc(this.A);this.G=new g.te(0,0,a.width,a.height);a=[];for(var b=this.A.document.getElementsByTagName("*"),c=0,d=b.length;c<d;c++){var e=b[c];if("IMG"==e.tagName||"IFRAME"==e.tagName){var f=we(this,e,e.src);if(f){if("IFRAME"==e.tagName){var k;try{k=(new xe(e.contentWindow)).B}catch(l){k=0}0<k&&(f.timing=k)}a.push(f)}}(f=this.A.getComputedStyle(e)["background-image"])&&
(f=xe.A.exec(f))&&1<f.length&&(f=we(this,e,f[1]))&&a.push(f)}this.C=a;this.F=this.A.performance.getEntriesByType("resource");this.K=this.A.performance.getEntriesByType("mark");k={};a=0;for(b=this.F.length;a<b;a++)c=this.F[a],k[c.name]=c.responseEnd;a=0;for(b=this.K.length;a<b;a++)c=this.K[a],"mark_iframe_loaded: "==c.name.slice(0,20)&&(k[c.name.slice(20)]=c.startTime);a=0;for(b=this.C.length;a<b;a++)c=this.C[a],c.timing||(c.timing=k[c.url]||0);this.H=Kaa(this);this.D=Laa(this);e=k=0;if(this.D.length)for(b=
a=0,c=this.D.length;b<c;b++)d=this.D[b],e=d.timing-e,0<e&&1>a&&(k+=(1-a)*e),e=d.timing,a=d.progress;this.B=Math.round(k||this.H);this.R=e}};
we=function(a,b,c){return c&&b.getBoundingClientRect&&(b=b.getBoundingClientRect(),b=new g.te(b.left,b.top,b.width,b.height),g.ue(b,a.G))?new ye(b,c):null};
Kaa=function(a){var b,c=a.A,d=c.performance.timing.navigationStart;if("msFirstPaint"in c.performance.timing)b=c.performance.timing.A-d;else if("chrome"in c&&"loadTimes"in c.chrome){var e=c.chrome.loadTimes(),f=e.firstPaintTime;if(0<f){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);f>=k&&(b=1E3*(f-k))}}if(void 0===b||0>b||12E4<b){b=c.performance.timing.responseStart-d;for(var l={},c=c.document.getElementsByTagName("head")[0].children,d=0,e=c.length;d<e;d++)f=c[d],"SCRIPT"==f.tagName&&f.src&&
!f.async?l[f.src]=!0:"LINK"==f.tagName&&"stylesheet"==f.rel&&f.href&&(l[f.href]=!0);a.F.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===b||a>b)b=a})}return Math.max(b,0)||0};
Laa=function(a){for(var b={0:0},c=0,d=a.H,e=0,f=a.C.length;e<f;e++){var k=a.C[e],l=d;k.timing>d&&(l=k.timing);b[l]||(b[l]=0);k=g.ve(k.region).og();b[l]+=k;c+=k}e=g.ve(a.G).og();0<e&&(e=.1*Math.max(e-c,0),d in b||(b[d]=0),b[d]+=e,c+=e);d=[];if(c){for(var n in b)a=new ze((0,window.parseFloat)(n),b[n]),d.push(a);d.sort(function(a,b){return a.timing-b.timing});
e=b=0;for(f=d.length;e<f;e++)a=d[e],b+=a.og,a.progress=b/c}return d};
ye=function(a,b){this.region=a;this.url=b};
ze=function(a,b){this.og=b;this.timing=a};
Be=function(a){Ae.mark&&(Maa.test(a)||(a="mark_"+a),Ae.mark(a))};
Naa=function(){if("cold"==Ce().yt_lt){var a=De(),b=Ee(),c;for(c in a)g.ua(c,"_")||"tick_"+c in b||Fe(c,a[c]);a=Ce();for(c in a)"info_"+c in b||Ge(c,a[c])}};
g.Ie=function(a,b,c){b||"_"==a[0]||Be(a);var d=De(c),e=b||(0,g.Vd)();d[a]&&(d["_"+a]=d["_"+a]||[d[a]],d["_"+a].push(e));d[a]=e;Fe(a,b,c)||g.He(!1,c);return d[a]};
Fe=function(a,b,c){Ee(c)["tick_"+a]=b;return g.kd("csi_on_gel")?(c=Je(c),"_start"==a?g.Wd("latencyActionBaselined",{clientActionNonce:c},Md,b):g.Wd("latencyActionTicked",{tickName:a,clientActionNonce:c},Md,b),!0):!1};
Le=function(a,b){Ke("yt_sts",a,void 0);g.Ie("_start",b,void 0)};
Ke=function(a,b,c){Ce(c)[a]=b;Ge(a,b,c)};
Ge=function(a,b,c){Ee(c)["info_"+a]=b;if(g.kd("csi_on_gel"))if(a in Me){var d={};a=Me[a];a in Oaa&&(b=!!b);d[a]=b;b=Je(c);d.clientActionNonce=b;g.Wd("latencyActionInfo",d,Md)}else g.Db(Error("Unknown label "+a+" logged with GEL CSI."))};
Pe=function(a){Ne(a);Paa();Oe(!1,a)};
Saa=function(){var a=g.v("TIMING_INFO",{}),b;for(b in a)Ke(b,a[b]);(a=g.Xd())&&Ke("csn",a);(a=g.v("PREVIOUS_ACTION",void 0))&&Ke("pa",a);a=Ce();a.p=g.v("CLIENT_PROTOCOL")||"unknown";a.t=g.v("CLIENT_TRANSPORT")||"unknown";Ae.now&&Ae.timing?(a=Ae.timing.navigationStart+Ae.now(),a=Math.round((0,g.G)()-a)):a=null;null!=a&&Ke("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&Ke("ba",1);Ke("yt_vis",Qaa());if("cold"==Ce().yt_lt){a=Ae.timing||{};a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=
window.chrome)if(b=b.loadTimes,g.ma(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.Ie("fpt",b);Qe(a);Ae.getEntriesByType&&Raa();a=g.v("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.v("TIMING_ACTION",void 0);a&&-1<a.indexOf(b)&&(a=(0,g.Vd)(),b=new xe,c=(0,g.Vd)(),0<b.B&&(Ke("si",b.B),g.Ie("vsc",Re(b.R)),g.Ie("sics",a),g.Ie("sice",c)));a=[];if(window.document.querySelector&&
Ae&&Ae.getEntriesByName)for(var d in Se)if(b=window.document.querySelector(d)){var c="",e=b.nodeName;"SCRIPT"==e?c=b.src:"LINK"==e&&(c=b.href);c&&(b=Ae.getEntriesByName(c))&&b[0]&&a.push(Se[d]+"."+Math.round(b[0].duration))}a.length&&Ke("rs",a.join(","))}};
Te=function(a){var b=De(a);if(b.aft)return b.aft;a=g.v((a||"")+"TIMING_AFT_KEYS",["ol"]);for(var c=a.length,d=0;d<c;d++){var e=b[a[d]];if(e)return e}return window.NaN};
Qe=function(a){g.Ie("nreqs",a.requestStart,void 0);g.Ie("nress",a.responseStart,void 0);g.Ie("nrese",a.responseEnd,void 0);0<a.redirectEnd-a.redirectStart&&(g.Ie("nrs",a.redirectStart,void 0),g.Ie("nre",a.redirectEnd,void 0));0<a.domainLookupEnd-a.domainLookupStart&&(g.Ie("ndnss",a.domainLookupStart,void 0),g.Ie("ndnse",a.domainLookupEnd,void 0));0<a.connectEnd-a.connectStart&&(g.Ie("ntcps",a.connectStart,void 0),g.Ie("ntcpe",a.connectEnd,void 0));a.secureConnectionStart>=a.navigationStart&&0<a.connectEnd-
a.secureConnectionStart&&(g.Ie("nstcps",a.secureConnectionStart,void 0),g.Ie("ntcpe",a.connectEnd,void 0))};
Re=function(a){return Math.round(Ae.timing.navigationStart+a)};
Raa=function(){var a=window.location.protocol,b=Ae.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.Ie("wfcs",Re(c.startTime)),g.Ie("wfce",Re(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.Ie("wffs",Re(b.startTime)),g.Ie("wffe",Re(b.responseEnd)))};
We=function(a){var b=De(a),c=Ce(a),d=b._start,e;for(e in b)if(g.ua(e,"_")&&g.ia(b[e])){var f=e.slice(1);if(f in Taa){var k=(0,g.Ue)(b[e],function(a){return Math.round(a-d)});
c["all_"+f]=k.join()}delete b[e]}f=!!c.ap;if(k=g.p("yt.timing.reportbuilder_")){if(k=k(b,c,a))Ve(k,f),Pe(a)}else{var l=g.v("CSI_SERVICE_NAME","youtube"),k={v:2,s:l,action:g.v((a||"")+"TIMING_ACTION",void 0)},n=c.srt;delete c.srt;void 0===b.srt&&(n||0===n||(n=Ae.timing||{},n=Math.max(0,n.responseStart-n.navigationStart),(0,window.isNaN)(n)&&c.pt&&(n=c.pt)),n||0===n)&&(c.srt=Math.round(n));if(c.h5jse){var u=window.location.protocol+g.p("ytplayer.config.assets.js");(u=Ae.getEntriesByName?Ae.getEntriesByName(u)[0]:
null)?c.h5jse=Math.round(c.h5jse-u.responseEnd):delete c.h5jse}b.aft=Te(a);Uaa(a)&&"youtube"==l&&(Ke("yt_lt","hot_bg",a),l=b.vc,u=b.pbs,delete b.aft,c.aft=Math.round(u-l));for(var w in c)"_"!=w.charAt(0)&&(k[w]=c[w]);b.ps=(0,g.Vd)();c={};w=[];for(e in b)"_"!=e.charAt(0)&&(l=Math.round(b[e]-d),g.kd("enable_negative_ticks")||(l=Math.max(l,0)),c[e]=l,w.push(e+"."+l));k.rt=w.join(",");(b=g.p("ytdebug.logTiming"))&&b(k,c);g.kd("navigation_only_csi_reset")||Pe(a);Ve(k,f,a);g.pe(Vaa,new qe(c.aft+(n||0)))}};
g.He=function(a,b){if(!Xe(b)||!g.kd("navigation_only_csi_reset")&&!b){var c=g.v((b||"")+"TIMING_ACTION",void 0),d=De(b);if(g.p("yt.timing."+(b||"")+"ready_")&&c&&d._start&&Te(b))if(a||b)We(b);else{var c=!0,e=g.v("TIMING_WAIT",[]);if(e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}c&&We(b)}}};
Ve=function(a,b,c){if(g.kd("debug_csi_data")){var d=g.p("yt.timing.csiData");d||(d=[],g.m("yt.timing.csiData",d,void 0));d.push({page:window.location.href,time:new Date,args:a})}var d="",e;for(e in a)d+="&"+e+"="+a[e];a="/csi_204?"+d.substring(1);window.navigator&&window.navigator.sendBeacon&&(!g.kd("beacon_abandoned_only")||b)?g.ke(a):g.je(a);Oe(!0,c)};
Ye=function(a){g.m("yt.timing.ready_",a,void 0)};
Je=function(a){var b=Ze(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(f){}c=Array(16);for(d=0;16>d;d++){e=(0,g.G)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if($e)for(d=1,e=0;e<$e.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^$e.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");Ze(a).nonce=b}return b};
De=function(a){return Ze(a).tick};
Ce=function(a){return Ze(a).info};
Ee=function(a){a=Ze(a);"gel"in a||(a.gel={});return a.gel};
Ze=function(a){return g.p("ytcsi."+(a||"")+"data_")||Ne(a)};
Ne=function(a){var b={tick:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
Xe=function(a){return!!g.p("yt.timing."+(a||"")+"pingSent_")};
Oe=function(a,b){g.m("yt.timing."+(b||"")+"pingSent_",a,void 0)};
af=function(a){if(!Xe(void 0)){if(!g.kd("send_empty_timing")){var b=g.v("CSI_SERVICE_NAME","youtube");if(!g.v("TIMING_ACTION",void 0)||!b)return}g.Ie("aa",void 0,void 0);Ke("ap",1,void 0);Ke("yt_fss",a,void 0);We(void 0)}};
Uaa=function(a){var b=De(a),c=b.pbr,d=b.vc,b=b.pbs;return c&&d&&b&&c<d&&d<b&&1==Ce(a).yt_pvis};
Qaa=function(){switch(g.jd()){case "hidden":return 0;case "visible":return 1;case "prerender":return 2;case "unloaded":return 3}return-1};
Waa=function(a){a=g.bf(a);return g.cf(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.cf=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.bf=function(a){a=g.be(a);return null===a?null:a.split(".").reverse()};
g.df=function(a,b){g.je("/gen_204?"+a,b)};
g.ef=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Xaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.hn=a.pageX;this.jn=a.pageY}};
g.gf=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Ua(g.ff,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.H=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.gf(a,b,c,d);if(e)return e;var e=++hf.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.ef(d);if(!g.fd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.ef(b);
b.currentTarget=a;return c.call(a,b)};
k=g.yb(k);a.addEventListener?("mouseenter"==b&&f?b="mouseover":"mouseleave"==b&&f?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.ff[e]=[a,b,c,k,d];return e};
g.J=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.y)(a,function(a){if(a in g.ff){var c=g.ff[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.ff[a]}}))};
g.jf=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.lf=function(){if(null==g.p("_lact",window)){var a=(0,window.parseInt)(g.v("LACT"),10),a=(0,window.isFinite)(a)?(0,g.G)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&kf();g.H(window.document,"keydown",kf);g.H(window.document,"keyup",kf);g.H(window.document,"mousedown",kf);g.H(window.document,"mouseup",kf);g.x("page-mouse",kf);g.x("page-scroll",kf);g.x("page-resize",kf)}};
kf=function(){null==g.p("_lact",window)&&(g.lf(),g.p("_lact",window));var a=(0,g.G)();g.m("_lact",a,window);g.z("USER_ACTIVE")};
g.mf=function(){var a=g.p("_lact",window);return null==a?-1:Math.max((0,g.G)()-a,0)};
nf=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ya(Yaa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ya(Zaa);this.params=a.params||g.Ya($aa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.of=function(a){a instanceof nf||(a=new nf(a));return a};
qf=function(){return null!=g.pf};
g.rf=function(){return g.pf?g.pf.invoke():null};
sf=function(){return(0,window.parseInt)(g.v("DCLKSTAT",0),10)};
g.tf=function(a){this.A=a||{cookie:""}};
g.vf=function(a){a=(a.A.cookie||"").split(g.uf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.xf=function(a,b,c,d){g.wf.set(""+a,b,c,"/",d||"youtube.com")};
g.Af=function(a,b,c){var d=g.v("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.be(window.location.href);e&&d.push(e);e=g.be(a);if(g.La(d,e)||!e&&g.ua(a,"/"))if(a=g.ce(a),a=g.de(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(yf(a,b,c),zf(b))):(yf(a,b),zf(b))};
yf=function(a,b,c){a="ST-"+g.Fa(a).toString(36);c=c||5;b=b?g.he(b):"";g.xf(a,b,c)};
zf=function(a){if(a){a=a.itct||a.ved;var b=g.p("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.Nd(a))}};
g.Bf=function(a,b,c){c=c||"";g.zc(window.location,g.ie(a,b||{})+c)};
g.Cf=function(a,b){b&&g.Af(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.Bf(a)};
g.Df=function(a,b,c){var d=g.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.Af(a,b);if(c)return!1;g.Cf(a);return!0};
g.Gf=function(){return g.Yc?"Webkit":g.Ef?"Moz":g.F?"ms":g.Ff?"O":null};
g.Hf=function(){return g.Yc?"-webkit":g.Ef?"-moz":g.F?"-ms":g.Ff?"-o":null};
g.Jf=function(a,b){var c=If[b];if(!c){var d=Ga(b),c=d;void 0===a.style[d]&&(d=g.Gf()+g.Ha(d),void 0!==a.style[d]&&(c=d));If[b]=c}return c};
g.Kf=function(a,b){var c=a.style[Ga(b)];return"undefined"!==typeof c?c:a.style[g.Jf(a,b)]||""};
g.Lf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Mf=function(a,b){a.style.height=g.Lf(b,!0)};
g.Nf=function(a,b){a.style.width=g.Lf(b,!0)};
g.Of=function(a,b){a.style.display=b?"":"none"};
g.Qf=function(){var a=g.wf.get("PREF",void 0);if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.Pf[d]=c.toString())}};
Rf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Sf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Tf=function(a){a=void 0!==g.Pf[a]?g.Pf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Uf=function(a,b){return!!((g.Tf("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.Vf=function(a,b){(a=g.E(a))&&a.style&&(g.Of(a,b),g.Gc(a,"hid",!b))};
g.Wf=function(a){return(a=g.E(a))?!("none"==a.style.display||g.B(a,"hid")):!1};
aba=function(a){if(a=g.E(a))g.Wf(a)?(g.Of(a,!1),g.C(a,"hid")):(g.Of(a,!0),g.D(a,"hid"))};
g.K=function(a){(0,g.y)(arguments,function(a){!g.ja(a)||a instanceof window.Element?g.Vf(a,!0):(0,g.y)(a,function(a){g.K(a)})})};
g.L=function(a){(0,g.y)(arguments,function(a){!g.ja(a)||a instanceof window.Element?g.Vf(a,!1):(0,g.y)(a,function(a){g.L(a)})})};
g.Xf=function(a){(0,g.y)(arguments,function(a){g.ja(a)?(0,g.y)(a,function(a){g.Xf(a)}):aba(a)})};
g.Zf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.p("window.navigator.plugins"),b=g.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,n,u;if(g.Yf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=n.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}n&&u&&n.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
$f=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
ag=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
bba=function(a){return g.bg?!$f(a,11,2):g.cg?!$f(a,11,3):!ag(a)};
dg=function(a,b,c){if(b){a=g.ka(a)?g.Qc(a):a;var d=g.Ya(c.attrs);d.tabindex=0;var e=g.Ya(c.params);e.flashvars=g.he(c.args);if(g.Yf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.gg=function(a,b){a=g.ka(a)?g.Qc(a):a;b=g.of(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Zf.getInstance();$f(c,b.minVersion)?(c=eg(b,c),dg(a,c,b)):fg(a,b,c)};
hg=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.of(a);var d=!!b,e=g.E(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var k=null;if(window.document.referrer){var l=window.document.referrer.substring(0,128);Waa(l)||(k=l)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Zf.getInstance();if($f(k,a.minVersion)){var l=eg(a,k),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=l||d)&&dg(f,l,a);bba(k)&&cba()}else fg(f,a,k);c&&c()}else g.zb(function(){hg(a,
b,c)},50)}};
fg=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Gb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="https://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
eg=function(a,b){var c;(c=ag(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!$f(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
cba=function(){var a=g.E("flash10-promo-div"),b=g.Uf(g.Qf.getInstance(),107);a&&!b&&g.K(a)};
g.ig=function(a,b){var c=a.match(dba);window.spf.style.load(a,c?c[1]:"",b)};
jg=function(a){g.qb.call(this);this.A=[];this.C=a||this};
kg=function(a,b,c,d){d=g.yb((0,g.q)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Ob:d})};
lg=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Ob)}};
og=function(a,b){g.qb.call(this);this.K=this.D=a;this.ha=b;this.H=!1;this.api={};this.la=this.T=null;this.X=new g.ub;g.tb(this,this.X);this.B={};this.G=this.Sa=this.C=this.hb=this.A=null;this.aa=!1;this.R=this.F=this.M=this.P=null;this.Xa={};this.Ib=["onReady"];this.ea=new jg(this);g.tb(this,this.ea);this.kb=null;this.Db=window.NaN;this.ga={};mg(this);this.ie("onDetailedError",(0,g.q)(this.WI,this));this.ie("onTabOrderChange",(0,g.q)(this.my,this));this.ie("onTabAnnounce",(0,g.q)(this.ep,this));this.ie("WATCH_LATER_VIDEO_ADDED",
(0,g.q)(this.ZI,this));this.ie("WATCH_LATER_VIDEO_REMOVED",(0,g.q)(this.$I,this));g.ng||(this.ie("onMouseWheelCapture",(0,g.q)(this.DI,this)),this.ie("onMouseWheelRelease",(0,g.q)(this.EI,this)));this.ie("onAdAnnounce",(0,g.q)(this.ep,this));this.Y=new jg(this);g.tb(this,this.Y);this.bb=!1;this.ab=null};
qg=function(a,b){a.hb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ha,a.A.attrs.id=a.ha);a.K.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ha;a.Sa||(a.Sa=pg(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.Nf(a.K,Number(c)||c);(c=a.A.attrs.height)&&g.Mf(a.K,Number(c)||c)};
rg=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
sg=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=$f(g.Zf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
vg=function(a,b){if((!b||(5!=(eba[b.errorCode]||5)?0:-1!=fba.indexOf(b.errorCode)))&&sg(a)){var c=tg(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.of(c));d.args.autoplay=1;d.args.html5_unavailable="1";qg(a,d);ug(a,"flash")}};
ug=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&sg(a))){if(!g.ca(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==wg)d=!0;else{a:{var e=c;c=g.p("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?gba:hba,f=0;f<e.length;f++)if(c.canPlayType(e[f])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=xg(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?sg(a)?"flash":"unsupported":"html5"}("flash"==b?a.cP:a.dP).call(a)}};
xg=function(a){var b=!0,c=tg(a);c&&a.A&&(a=a.A,b=g.A(c,"version")==a.assets.js);return b&&!!g.p("yt.player.Application.create")};
tg=function(a){var b=g.E(a.C);!b&&a.K&&a.K.querySelector&&(b=a.K.querySelector("#"+a.C));return b};
yg=function(a,b,c){var d=b[c];return function(){try{return a.kb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.kb=e,g.Db(e,"WARNING"))}}};
mg=function(a){a.H=!1;if(a.la)for(var b in a.B)a.la(b,a.B[b]);for(var c in a.ga)g.Bb((0,window.parseInt)(c,10));a.ga={};a.T=null;a.la=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.q)(a.ie,a);a.api.removeEventListener=(0,g.q)(a.fN,a);a.api.destroy=(0,g.q)(a.dispose,a);a.api.getLastError=(0,g.q)(a.Nz,a);a.api.getPlayerType=(0,g.q)(a.cA,a);a.api.getCurrentVideoConfig=(0,g.q)(a.kz,a);a.api.loadNewVideoConfig=(0,g.q)(a.Bo,a);a.api.isReady=(0,g.q)(a.qP,a)};
pg=function(a,b){var c=b;if("string"==typeof b){if(a.Xa[b])return a.Xa[b];c=function(){var a=g.p(b);a&&a.apply(g.da,arguments)};
a.Xa[b]=c}return c?c:null};
iba=function(a,b){var c="ytPlayer"+b+a.ha;a.B[b]=c;g.da[c]=function(c){var e=g.zb(function(){a.isDisposed()||(a.X.qa(b,c),g.Wa(a.ga,String(e)))},0);
g.Xa(a.ga,String(e),!0)};
return c};
zg=function(a){return(a=tg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
Ag=function(a){g.Ie("dcp");a.cancel();mg(a);a.G=null;a.A&&(a.A.loaded=!1);var b=tg(a);"html5"==zg(a)?a.M=b:b&&b.destroy&&b.destroy();g.bd(a.D);lg(a.ea);a.F=null;a.R=null};
g.Dg=function(a,b){a=g.ka(a)?g.Qc(a):a;b=g.of(b);var c=g.Bg+"_"+g.qa(a),d=g.Cg[c];if(d)return d.Bo(b),d.api;d=new og(a,c);g.Cg[c]=d;g.z("player-added",d.api);g.rb(d,g.r(jba,d));g.zb(function(){d.Bo(b)},0);
return d.api};
jba=function(a){g.Cg[a.getId()]=null};
g.Eg=function(a){a=g.E(a);if(!a)return null;var b=g.Bg+"_"+g.qa(a),c=g.Cg[b];c||(c=new og(a,b),g.Cg[b]=c);return c.api};
g.Fg=function(){return g.B(g.E("page-container"),"remote-connected")};
kba=function(){g.m("yt.abuse.botguardInitialized",qf,void 0);g.m("yt.abuse.invokeBotguard",g.rf,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",sf,void 0);g.m("yt.player.exports.navigate",g.Df,void 0);g.m("yt.player.embed",g.Dg,void 0);g.m("yt.player.getPlayerByElement",g.Eg,void 0);g.m("yt.util.activity.init",g.lf,void 0);g.m("yt.util.activity.getTimeSinceActive",g.mf,void 0);g.m("yt.util.activity.setTimestamp",kf,void 0);var a=g.p("ytplayer.config");Gg(a);g.p("ytspf.enabled")&&(Hg=g.Ab(Ig,5E3),
(a=g.Jg())?(a.addEventListener("onReady",Ig),a.addEventListener("onStateChange",Ig)):Kg("unable to init PP monitor"))};
Gg=function(a){for(var b in g.Cg){var c=g.Cg[b];c&&c.cancel()}if(a=a||null){b=g.Jg();var d=!0,c=g.Lg;g.Lg=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(Mg="",g.Dg("player-api",a)):b.playVideo();a=g.of(a);a.loaded=!0}Ig();g.m("ytplayer.config",a,void 0)};
g.Jg=function(){var a=g.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
Ig=function(){var a=g.Jg();if(a){var b;b=g.E("player");b=!b||g.B(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.v("PAGE_NAME"),e=g.Fg();!c||d||e||(Kg("PP playing off watch (paused)"),a.pauseVideo());b&&d?Kg("PP off-screen on watch"):b||d||Kg("PP !off-screen off watch")}};
Kg=function(a){var b=g.v("PAGE_NAME");b&&(b=[b,Mg,g.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.Db(Error(a),"WARNING"))};
g.Ng=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Zf=!1;this.hv=!0};
g.Og=function(a,b){g.Ng.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pn=!1;this.ub=null;a&&this.init(a,b)};
g.Qg=function(a){return!(!a||!a[Pg])};
mba=function(a,b,c,d,e){this.listener=a;this.A=null;this.src=b;this.type=c;this.wh=!!d;this.od=e;this.key=++lba;this.Vg=this.Oi=!1};
Rg=function(a){a.Vg=!0;a.listener=null;a.A=null;a.src=null;a.od=null};
Sg=function(a){this.src=a;this.A={};this.C=0};
g.Ug=function(a,b,c,d,e,f){var k=b.toString();b=a.A[k];b||(b=a.A[k]=[],a.C++);var l=Tg(b,c,e,f);-1<l?(a=b[l],d||(a.Oi=!1)):(a=new mba(c,a.src,k,!!e,f),a.Oi=d,b.push(a));return a};
Vg=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=g.Oa(a.A[c],b);d&&(Rg(b),0==a.A[c].length&&(delete a.A[c],a.C--));return d};
g.Wg=function(a,b,c,d,e){a=a.A[b.toString()];b=-1;a&&(b=Tg(a,c,d,e));return-1<b?a[b]:null};
Tg=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Vg&&f.listener==b&&f.wh==!!c&&f.od==d)return e}return-1};
g.Xg=function(a,b,c,d,e){if(g.ia(b)){for(var f=0;f<b.length;f++)g.Xg(a,b[f],c,d,e);return null}c=g.Yg(c);return g.Qg(a)?a.O(b,c,d,e):g.Zg(a,b,c,!1,d,e)};
g.Zg=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=!!e,l=g.$g(a);l||(a[ah]=l=new Sg(a));c=g.Ug(l,b,c,d,e,f);if(c.A)return c;d=nba();c.A=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(bh(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");ch++;return c};
nba=function(){var a=oba,b=dh?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);
if(!c)return c};
return b};
g.eh=function(a,b,c,d,e){if(g.ia(b))for(var f=0;f<b.length;f++)g.eh(a,b[f],c,d,e);else c=g.Yg(c),g.Qg(a)?a.Va(b,c,d,e):a&&(a=g.$g(a))&&(b=g.Wg(a,b,c,!!d,e))&&g.fh(b)};
g.fh=function(a){if(g.la(a)||!a||a.Vg)return!1;var b=a.src;if(g.Qg(b))return Vg(b.Y,a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.wh):b.detachEvent&&b.detachEvent(bh(c),d);ch--;(c=g.$g(b))?(Vg(c,a),0==c.C&&(c.src=null,b[ah]=null)):Rg(a);return!0};
bh=function(a){return a in gh?gh[a]:gh[a]="on"+a};
ih=function(a,b,c,d){var e=!0;if(a=g.$g(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.wh==c&&!f.Vg&&(f=hh(f,d),e=e&&!1!==f)}return e};
hh=function(a,b){var c=a.listener,d=a.od||a.src;a.Oi&&g.fh(a);return c.call(d,b)};
oba=function(a,b){if(a.Vg)return!0;if(!dh){var c=b||g.p("window.event"),d=new g.Og(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(n){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.Zf&&0<=k;k--){d.currentTarget=c[k];var l=ih(c[k],f,!0,d),e=e&&l}for(k=0;!d.Zf&&k<c.length;k++)d.currentTarget=c[k],l=ih(c[k],f,!1,d),e=e&&l}return e}return hh(a,new g.Og(b,
this))};
g.$g=function(a){a=a[ah];return a instanceof Sg?a:null};
g.Yg=function(a){if(g.ma(a))return a;a[jh]||(a[jh]=function(b){return a.handleEvent(b)});
return a[jh]};
g.kh=function(){g.qb.call(this);this.Y=new Sg(this);this.qx=this;this.so=null};
lh=function(a,b,c,d){b=a.Y.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var k=b[f];if(k&&!k.Vg&&k.wh==c){var l=k.listener,n=k.od||k.src;k.Oi&&Vg(a.Y,k);e=!1!==l.call(n,d)&&e}}return e&&0!=d.hv};
g.mh=function(a,b,c){if(g.ma(a))c&&(a=(0,g.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,g.q)(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:g.da.setTimeout(a,b||0)};
g.nh=function(a){g.da.clearTimeout(a)};
g.oh=function(a,b,c){g.qb.call(this);this.A=a;this.B=b||0;this.C=c;this.Hc=(0,g.q)(this.Rl,this)};
uba=function(){ph++;var a=g.Uc(),b=new g.te(0,0,a.width,a.height);Ke("vps",a.width+"."+a.height);g.Ie("vpc");var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0;qh.start();for(var f=0;f<c;f++){var k=a[f];if(rh(k,b)){var l=pba(k);l.then(qba);d.push(l);sh.push(l);k.loadTime||(e=!1)}}e&&Ke("yt_eil",1);Ke("vpni",d.length);g.Ie("vpcc");b=g.yd(d).then(rba);g.Ad(b,sba);b.then(tba);sh.push(b);return b};
tba=function(){qh.stop()};
sba=function(){g.Ie("vpr")};
rh=function(a,b){for(var c=a,d=window.document.body;c!=d;){var e=g.hd(c);if(e in th)break;var f=window.getComputedStyle(c);if("none"==f.display||"hidden"==f.visibility)return!1;f=c.getBoundingClientRect();if(!(b.left<=f.left+f.width&&f.left<=b.left+b.width&&b.top<=f.top+f.height&&f.top<=b.top+b.height))return!1;th[e]=!0;c=c.parentElement}return!0};
rba=function(a){for(var b=g.Uc(),b=new g.te(0,0,b.width,b.height),c=0,d=0,e=a.length;d<e;d++){var f=a[d].time;rh(a[d].C,b)&&c<f&&(c=f)}return c};
pba=function(a){var b=ph;return new g.td(function(c,d){var e={C:a,time:0};if(a.loadTime)e.time=(0,window.parseInt)(a.loadTime,10),c(e);else{var f=g.H(a,"load",function(){ph!=b&&(g.J(f),d());if(a.loadTime){var k=(0,window.parseInt)(a.loadTime,10);g.J(f);e.time=k;c(e)}});
uh.push(f)}})};
qba=function(a){qh.start();Ke("vpil",++vh);a=a.time;wh<a&&(wh=a,g.Ie("lim",a))};
vba=function(){g.Ie("vptl",wh);g.Ie("vpl",wh)};
zh=function(){g.Ie("ol");g.v("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Ie("cpt");xh()},0)}):window.document.hidden?(g.Ie("cpt"),xh()):(0,window.setTimeout)(function(){g.Ie("cpt");
xh()},0):xh();
g.v("CSI_VIEWPORT")&&(yh=uba(),yh.then(function(a){g.Ie("vpl",a);yh=null},function(){}))};
xh=function(){Ah("init");var a=g.v("PAGE_NAME",void 0);a&&Ah("init-"+a)};
Ah=function(a){g.Ob()?Bh.push(g.Pb(g.r(g.Nb,a),0)):g.z(a)};
Ch=function(){g.Tb(Bh);Bh.length=0;for(var a=sh.length,b=0;b<a;b++)sh[b].cancel();wh=vh=sh.length=0;th={};g.J(uh);uh.length=0;yh&&(yh.cancel(),yh=null);(a=g.v("PAGE_NAME",void 0))&&g.Nb("dispose-"+a);g.Nb("dispose")};
wba=function(){zh()};
xba=function(){g.v("TIMING_REPORT_ON_UNLOAD")&&g.He(!0);af("u");Ch();g.Nb("pageunload")};
Dh=function(){kf()};
Eh=function(){window.yt_spf_loaded_history=!0;g.v("EXP_LACT_HISTORY")&&kf()};
Jh=function(){Fh=1;Gh=Hh=0;g.v("TIMING_REPORT_ON_UNLOAD")&&g.He(!0);af("n");Pe();Le("n");Be("nr");Ih(yba);g.Nb("navigate")};
Nh=function(a){a=a.detail.part||a.detail.partial;g.Ie("nc"+Hh);++Hh;if(!a.data||!a.data.deferDispose){var b=1==Fh;Fh=2;b?(Ih(zba),Kh()):Ih(Aba);if(b=a.data&&a.data.swfcfg)Lh(a.timing,b.args),Mh(b)}};
Oh=function(){g.Ie("np"+Gh);++Gh};
Ph=function(a){a=a.detail.response;var b=1==Fh;Fh=3;b&&(Ih(Bba),Kh());if(b=a.data&&a.data.swfcfg)Lh(a.timing,b.args),Mh(b)};
Sh=function(a){g.Ie("nd");a=a.detail.response;g.Qh=a.cacheKey;a=a.timing;var b=window._spf_state;Ke("yt_nav",b&&b["nav-counter"]||0);Le("ne",a.responseStart);Ke("srt",Math.max(0,a.responseStart-a.navigationStart));Ke("yt_lt",a.spfCached?"hot":"warm");Ke("yt_pft",+!!a.spfPrefetched);g.Ie("pfs",a.fetchStart);g.Ie("pfrs",a.responseStart);"redirectStart"in a&&Qe(a);Ih(Rh);window.document.getElementById("content").style.height="";zh();Fh=0};
Th=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Db(a)};
Uh=function(a){g.df(g.he({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
Dba=function(){Cba();g.xb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
Eba=function(){};
Kh=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Ch();var a=g.v("TIMING_ACTION"),b;for(b in g.wb)delete g.wb[b];g.xb("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.Jg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())Mg=b,(b=g.E("movie_player"))&&b.stopVideo?(b.stopVideo(),Mg="recovered"):Mg="missing2"}else Mg="missing";Ig()};
Mh=function(a){"cfg"in De(void 0)||g.Ie("cfg");Gg(a)};
Ih=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Rb(Vh);Vh=g.Qb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.Bb(Wh);Wh=g.zb(function(){b.className=e},c)},0)};
Cba=function(){var a=Rh[0]+50;g.Bb(Wh);Wh=g.zb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
Lh=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.y)(Fba,function(a){a in b&&(delete b[a],e.push(a))});
g.v("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.df(g.he(c)))};
Gba=function(a){g.Xh&&!g.Yh&&!g.Zh&&!g.$h&&a.pushManager&&g.v("LOGGED_IN",void 0)&&"default"==window.Notification.permission&&a.pushManager.subscribe({userVisibleOnly:!0}).then(function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_register"})},function(){})};
Hba=function(){var a="/sw.js",b=g.v("SERVICE_WORKER_VFL",void 0);b&&(a+="?vfl="+b);window.navigator.serviceWorker.register(a,{scope:"/"});g.kd("service_worker_push_enabled")&&window.navigator.serviceWorker.ready.then(Gba)};
Iba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"})};
ai=function(){g.Ub.call(this,"www/base");this.B=0};
bi=function(a){(a=a.detail.name)&&Xb(a)};
g.aa=[];g.ci=g.ci||{};g.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.G=Date.now||function(){return+new Date};ra[" "]=g.fa;g.t(g.ta,Error);g.ta.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Ba=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.di=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.Jba=2147483648*Math.random()|0;g.Ka=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ka(a))return g.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.Kba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ka(a))return g.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.Fc=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.ka(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var n=k[l];
b.call(c,n,l,a)&&(e[f++]=n)}return e};
g.Ue=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.ka(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.ei=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.q)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.y)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.fi=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.gi=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.hi=g.Qa(!1);g.ii=g.Qa(!0);g.ji=g.Qa(null);var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var ki=g.da.navigator;if(ki){var li=ki.userAgent;if(li){g.ab=li;break a}}g.ab=""};var pb;fb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var mb=new fb(function(){return new ib},function(a){a.reset()},100);
hb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
ib.prototype.set=function(a,b){this.pe=a;this.scope=b;this.next=null};
ib.prototype.reset=function(){this.next=this.scope=this.pe=null};var jb,kb=!1,lb=new hb;g.qb.prototype.Md=!1;g.qb.prototype.isDisposed=function(){return this.Md};
g.qb.prototype.dispose=function(){this.Md||(this.Md=!0,this.U())};
g.qb.prototype.U=function(){if(this.Kb)for(;this.Kb.length;)this.Kb.shift()()};g.t(g.ub,g.qb);g.h=g.ub.prototype;g.h.subscribe=function(a,b,c){var d=this.sd[a];d||(d=this.sd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.sd[a]){var d=this.A;if(a=g.Ja(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.td(a)}return!1};
g.h.td=function(a){var b=this.A[a];if(b){var c=this.sd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.fa):(c&&g.Oa(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.qa=function(a,b){var c=this.sd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.td(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.sd[a];b&&((0,g.y)(b,this.td,this),delete this.sd[a])}else this.A.length=0,this.sd={}};
g.h.pb=g.ba(1);g.h.U=function(){g.ub.L.U.call(this);this.clear();this.C.length=0};g.wb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.wb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Eb=window.yt&&window.yt.msgs_||g.p("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Eb,void 0);g.Vd=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Yf="Microsoft Internet Explorer"==window.navigator.appName;var Lba=g.p("yt.pubsub.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.td;g.ub.prototype.publish=g.ub.prototype.qa;g.ub.prototype.clear=g.ub.prototype.clear;g.m("yt.pubsub.instance_",Lba,void 0);var Jb=g.p("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Jb,void 0);var Lb=g.p("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Lb,void 0);var Kb=g.p("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Kb,void 0);var Ib=g.p("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Ib,void 0);g.h=g.Ub.prototype;g.h.sN=function(){this.Rj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.sN,this),this.subscribe("dispose-"+a,this.dispose,this),g.v("PAGE_NAME")==a&&g.Vb(this))},this)};
g.h.init=function(){g.Rb(this.C);this.A=2;this.H&&this.H()};
g.h.Rj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Rb(this.C);this.F&&this.F()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Db(a)}};
g.h.subscribe=function(a,b,c){a=g.x(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Mb(this.D);this.D=[]};var Wb=g.p("yt.modules.registry_")||{};g.m("yt.modules.registry_",Wb,void 0);var taa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.Mba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Nba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.mi=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.ac.prototype.Sf=!0;g.ac.prototype.Qe=function(){return this.A};
g.ac.prototype.toString=function(){return"Const{"+this.A+"}"};
var $b={};dc.prototype.Sf=!0;var cc={};dc.prototype.Qe=function(){return this.A};
var paa=fc(""),oaa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.ic.prototype.Sf=!0;g.ic.prototype.Qe=function(){return this.A};
g.ic.prototype.um=!0;g.ic.prototype.Cg=function(){return 1};
var qaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,hc={};g.kc("about:blank");g.nc.prototype.Sf=!0;g.nc.prototype.Qe=function(){return this.A};
g.nc.prototype.um=!0;g.nc.prototype.Cg=function(){return 1};
var mc={};var uc,saa,raa,pc;g.qc.prototype.um=!0;g.qc.prototype.Cg=function(){return this.C};
g.qc.prototype.Sf=!0;g.qc.prototype.Qe=function(){return this.A};
uc=/^[a-zA-Z0-9-]+$/;saa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};raa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};pc={};g.Oba=g.sc("<!DOCTYPE html>",0);g.ni=g.sc("",0);g.oi=g.sc("<br>",0);var Bc={};var uaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,vaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Pba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.h=g.Hc.prototype;g.h.clone=function(){return new g.Hc(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.x*=a;this.y*=c;return this};g.h=g.Ic.prototype;g.h.clone=function(){return new g.Ic(this.width,this.height)};
g.h.og=function(){return this.width*this.height};
g.h.aspectRatio=function(){return this.width/this.height};
g.h.isEmpty=function(){return!this.og()};
g.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.width*=a;this.height*=c;return this};var ri,si,Lc,wi;g.Ff=g.bb("Opera");g.F=g.cb();g.pi=g.bb("Edge");g.qi=g.pi||g.F;g.Ef=g.bb("Gecko")&&!(g.ya(g.ab.toLowerCase(),"webkit")&&!g.bb("Edge"))&&!(g.bb("Trident")||g.bb("MSIE"))&&!g.bb("Edge");g.Yc=g.ya(g.ab.toLowerCase(),"webkit")&&!g.bb("Edge");g.Yc&&g.bb("Mobile");g.cg=g.bb("Macintosh");g.bg=g.bb("Windows");g.Qba=g.bb("Linux")||g.bb("CrOS");ri=g.da.navigator||null;ri&&g.ya(ri.appVersion||"","X11");g.Rba=g.bb("Android");g.Zh=g.Jc();g.$h=g.bb("iPad");g.Sba=g.bb("iPod");
a:{var ti="",ui=function(){var a=g.ab;if(g.Ef)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.pi)return/Edge\/([\d\.]+)/.exec(a);if(g.F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Yc)return/WebKit\/(\S+)/.exec(a);if(g.Ff)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
ui&&(ti=ui?ui[1]:"");if(g.F){var vi=Kc();if(null!=vi&&vi>(0,window.parseFloat)(ti)){si=String(vi);break a}}si=ti}g.Mc=si;Lc={};wi=g.da.document;g.Oc=wi&&g.F?Kc()||("CSS1Compat"==wi.compatMode?(0,window.parseInt)(g.Mc,10):5):void 0;var waa;waa=!g.F||g.Pc(9);g.Tba=!g.Ef&&!g.F||g.F&&g.Pc(9)||g.Ef&&g.Nc("1.9.1");g.xi=g.F&&!g.Nc("9");g.Uba=g.F||g.Ff||g.Yc;g.Vba=g.F&&!g.Pc(9);var Rc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};var Aaa=g.Yc?"webkit":g.Ef?"moz":g.F?"ms":g.Ff?"o":"",gd=g.p("yt.dom.getNextId_");if(!gd){gd=function(){return++Wba};
g.m("yt.dom.getNextId_",gd,void 0);var Wba=0};g.ld.prototype.Sb=function(a){var b=[];nd(this,a,b);return b.join("")};
var pd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Baa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;ud.prototype.reset=function(){this.context=this.C=this.B=this.A=null;this.D=!1};
var vd=new fb(function(){return new ud},function(a){a.reset()},100);
g.td.prototype.then=function(a,b,c){return zd(this,g.ma(a)?a:null,g.ma(b)?b:null,c)};
g.qd(g.td);g.td.prototype.cancel=function(a){0==this.A&&nb(function(){var b=new g.Gd(a);Bd(this,b)},this)};
g.td.prototype.R=function(a){this.A=0;g.sd(this,2,a)};
g.td.prototype.Y=function(a){this.A=0;g.sd(this,3,a)};
g.td.prototype.G=function(){for(var a;a=Cd(this);)Dd(this,a,this.A,this.K);this.H=!1};
var Id=eb;g.t(g.Gd,g.ta);g.Gd.prototype.name="cancel";var Ld=null;Md.prototype.D=function(){var a=g.p("gapi.config.update");a("googleapis.config/auth/useFirstPartyAuth",!0);var b=this.A.apiaryHost;g.va(g.Aa(b))||a("googleapis.config/root",(-1==b.indexOf("://")?"//":"")+b);b=this.A.op;g.va(g.Aa(b))||a("googleapis.config/root-1p",(-1==b.indexOf("://")?"//":"")+b);a("googleapis.config/sessionIndex",g.v("SESSION_INDEX"));g.p("gapi.client.setApiKey")(this.A.innertubeApiKey)};
Md.prototype.C=function(){return{context:g.Kd(this.A)}};
Md.prototype.B=function(a,b,c){var d,e=!1;0<c.timeout&&(d=g.zb(function(){e||(e=!0,c.Cc&&c.Cc())},c.timeout));
Gaa(this,a,b,function(a){if(!e)if(e=!0,d&&g.Bb(d),a)c.W&&c.W(a);else if(c.onError)c.onError()})};var Haa,Pd;Haa={log_event:"events",log_interaction:"interactions"};g.Ud={};Pd={};g.Td=0;g.Od=g.p("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.Od,void 0);g.yi="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.$d=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;g.ng=g.bb("Firefox");g.zi=g.Jc()||g.bb("iPod");g.Ai=g.bb("iPad");g.Yh=g.bb("Android")&&!(g.db()||g.bb("Firefox")||g.bb("Opera")||g.bb("Silk"));g.Xh=g.db();g.Bi=g.bb("Safari")&&!(g.db()||g.bb("Coast")||g.bb("Opera")||g.bb("Edge")||g.bb("Silk")||g.bb("Android"))&&!(g.Jc()||g.bb("iPad")||g.bb("iPod"));var le={},Jaa=0;g.me.prototype.Sb=function(){return{version:this.version,args:this.args}};
g.ne.prototype.toString=function(){return this.topic};var Xba=g.p("yt.pubsub2.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.td;g.ub.prototype.publish=g.ub.prototype.qa;g.ub.prototype.clear=g.ub.prototype.clear;g.m("yt.pubsub2.instance_",Xba,void 0);g.Ci=g.p("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.Ci,void 0);g.Di=g.p("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.Di,void 0);g.Ei=g.p("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.Ei,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var $e=(0,g.G)().toString();var Ae=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.t(qe,g.me);var Vaa=new g.ne("timing-sent",qe);g.h=g.re.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.re(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.se(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.h=g.te.prototype;g.h.clone=function(){return new g.te(this.left,this.top,this.width,this.height)};
g.h.contains=function(a){return a instanceof g.Hc?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
g.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};ye.prototype.toString=function(){return this.region.toString()+": "+this.timing+" => "+this.url};
ze.prototype.toString=function(){return["progress",this.progress,"timing",this.timing,"area",this.og].join(": ")};
xe.C=.1;xe.A=/url\(["']?(http[^'"\)]+)['"]?\)/i;xe.B="mark_iframe_loaded: ";xe.D=20;var Taa={vc:!0},Maa=/^mark_/i,Se={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="player-plasma-phone/base"]':"mpppj",'script[name="player-plasma-tablet/base"]':"mpptj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},
Me={ad_at:"adType",cpn:"clientPlaybackNonce",csn:"clientScreenNonce",yt_lt:"loadType",yt_ad:"isMonetized",yt_ad_pr:"prerollAllowed",yt_red:"isRedSubscriber",yt_vis:"isVisible"},Oaa=["isMonetized","prerollAllowed","isRedSubscriber","isVisible"],Paa=(0,g.q)(Ae.clearResourceTimings||Ae.webkitClearResourceTimings||Ae.mozClearResourceTimings||Ae.msClearResourceTimings||Ae.oClearResourceTimings||g.fa,Ae);g.ef.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.ef.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.ef.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Xaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.ff=g.p("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.ff,void 0);var hf=g.p("yt.events.counter_")||{count:0};g.m("yt.events.counter_",hf,void 0);var Yaa={enablejsapi:1},Zaa={},$aa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};nf.prototype.clone=function(){var a=new nf,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Ya(c):a[b]=c}return a};g.pf=null;g.uf=/\s*;\s*/;g.h=g.tf.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.G)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.uf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Lb=g.ba(2);g.h.lb=g.ba(3);g.h.isEmpty=function(){return!this.A.cookie};
g.h.pb=g.ba(0);g.h.oe=g.ba(4);g.h.clear=function(){for(var a=g.vf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.wf=new g.tf("undefined"==typeof window.document?null:window.document);g.wf.C=3950;g.Fi=g.F?"focusin":"DOMFocusIn";g.Gi=g.F?"focusout":"DOMFocusOut";g.Hi=g.Yc?"webkitTransitionEnd":g.Ff?"otransitionend":"transitionend";var If;If={};g.Ii=g.Ef?"MozUserSelect":g.Yc||g.pi?"WebkitUserSelect":null;g.ga(g.Qf);g.Pf=g.p("yt.prefs.UserPrefs.prefs_")||{};g.m("yt.prefs.UserPrefs.prefs_",g.Pf,void 0);g.h=g.Qf.prototype;g.h.get=function(a,b){Sf(a);Rf(a);var c=void 0!==g.Pf[a]?g.Pf[a].toString():null;return null!=c?c:b?b:""};
g.h.set=function(a,b){Sf(a);Rf(a);if(null==b)throw"ExpectedNotNull";g.Pf[a]=b.toString()};
g.h.remove=function(a){Sf(a);Rf(a);delete g.Pf[a]};
g.h.save=function(){var a;a=[];for(var b in g.Pf)a.push(b+"="+(0,window.escape)(g.Pf[b]));a=a.join("&");g.xf("PREF",a,63072E3)};
g.h.clear=function(){g.Pf={}};g.Ji=g.Ra(function(){if(g.F)return g.Nc("10.0");var a=window.document.createElement("DIV"),b=g.Hf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.yc(a,g.wc("div",{style:c}));return""!=g.Kf(a.firstChild,"transition")});g.ga(g.Zf);g.Zf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var dba=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var wg;var Ki=g.ab,Ki=Ki.toLowerCase();if(g.ya(Ki,"android")){var Li=Ki.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Li)wg=Number(Li[1]);else{var Mi={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Ni=Ki.match("("+g.Ta(Mi).join("|")+")");wg=Ni?Mi[Ni[0]]:0}}else wg=void 0;var gba=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],hba=['audio/mp4; codecs="mp4a.40.2"'];g.t(jg,g.qb);jg.prototype.Va=function(a){for(var b=0;b<this.A.length;b++)if(this.A[b]==a){this.A.splice(b,1);a.target.removeEventListener(a.name,a.Ob);break}};
jg.prototype.U=function(){lg(this);jg.L.U.call(this)};var eba={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.t(og,g.qb);var fba=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=og.prototype;g.h.getId=function(){return this.ha};
g.h.Bo=function(a,b){this.isDisposed()||(qg(this,a),ug(this,b),this.H&&rg(this))};
g.h.kz=function(){return this.hb};
g.h.dP=function(){if(!this.aa){var a=xg(this);a&&"html5"==zg(this)?(this.G="html5",this.H||this.Ug()):(Ag(this),this.G="html5",a&&this.M?(this.D.appendChild(this.M),this.Ug()):(this.A.loaded=!0,this.P=(0,g.q)(function(){var a=this.D,c=this.A.clone();g.p("yt.player.Application.create")(a,c);this.Ug()},this),this.aa=!0,a?this.P():(g.Dc(this.A.assets.js,this.P),g.ig(this.A.assets.css))))}};
g.h.cP=function(){var a=this.A.clone();if(!this.F){var b=tg(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,kg(this.ea,this.F,"focus",this.Gt),this.R=window.document.createElement("span"),this.R.tabIndex=0,kg(this.ea,this.R,"focus",this.Gt),g.cd(this.F,b),g.dd(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==zg(this)?(this.G="flash",this.H||hg(a,!1,(0,g.q)(this.Ug,this))):(Ag(this),this.G="flash",this.A.loaded=!0,g.gg(this.D,a),
this.Ug())};
g.h.Gt=function(){tg(this).focus()};
g.h.Ug=function(){if(!this.isDisposed()){var a=tg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))vg(this);else{mg(this);this.H=!0;a=tg(this);a.addEventListener&&(this.T=yg(this,a,"addEventListener"));a.removeEventListener&&(this.la=yg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=yg(this,
a,d))}for(var e in this.B)this.T(e,this.B[e]);rg(this);this.Sa&&this.Sa(this.api);this.X.qa("onReady",this.api)}else this.Db=g.zb((0,g.q)(this.Ug,this),50)}};
g.h.qP=function(){return this.H};
g.h.ie=function(a,b){if(!this.isDisposed()){var c=pg(this,b);if(c){if(!g.La(this.Ib,a)&&!this.B[a]){var d=iba(this,a);this.T&&this.T(a,d)}this.X.subscribe(a,c);"onReady"==a&&this.H&&g.zb(g.r(c,this.api),0)}}};
g.h.fN=function(a,b){if(!this.isDisposed()){var c=pg(this,b);c&&this.X.unsubscribe(a,c)}};
g.h.my=function(a){a=a?zaa:yaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.ep=function(a){g.z("a11y-announce",a)};
g.h.WI=function(a){vg(this,a)};
g.h.ZI=function(a){g.z("WATCH_LATER_VIDEO_ADDED",a)};
g.h.$I=function(a){g.z("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.DI=function(){this.bb||(g.Xh?(this.ab=g.Xc(window.document),kg(this.Y,window,"scroll",this.nL),kg(this.Y,this.D,"touchmove",this.QK)):(kg(this.Y,this.D,"mousewheel",this.Vt),kg(this.Y,this.D,"wheel",this.Vt)),this.bb=!0)};
g.h.EI=function(){lg(this.Y);this.bb=!1};
g.h.Vt=function(a){g.jf(a)};
g.h.nL=function(){window.scrollTo(this.ab.x,this.ab.y)};
g.h.QK=function(a){a.preventDefault()};
g.h.cA=function(){return this.G||zg(this)};
g.h.Nz=function(){return this.kb};
g.h.cancel=function(){if(this.P){var a=this.P,b=g.Cc(this.A.assets.js);window.spf.script.ignore(b,a)}g.Bb(this.Db);this.aa=!1};
g.h.U=function(){Ag(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.Db(b)}this.Xa=null;for(var a in this.B)g.da[this.B[a]]=null;this.hb=this.A=this.api=null;delete this.D;delete this.K;og.L.U.call(this)};g.Cg={};g.Bg="player_uid_"+(1E9*Math.random()>>>0);var Yba=g.p("yt.abuse.botguardInitialized")||qf;g.m("yt.abuse.botguardInitialized",Yba,void 0);var Zba=g.p("yt.abuse.invokeBotguard")||g.rf;g.m("yt.abuse.invokeBotguard",Zba,void 0);var $ba=g.p("yt.abuse.dclkstatus.checkDclkStatus")||sf;g.m("yt.abuse.dclkstatus.checkDclkStatus",$ba,void 0);var aca=g.p("yt.player.exports.navigate")||g.Df;g.m("yt.player.exports.navigate",aca,void 0);var bca=g.p("yt.player.embed")||g.Dg;g.m("yt.player.embed",bca,void 0);var cca=g.p("yt.player.getPlayerByElement")||g.Eg;
g.m("yt.player.getPlayerByElement",cca,void 0);var dca=g.p("yt.util.activity.init")||g.lf;g.m("yt.util.activity.init",dca,void 0);var eca=g.p("yt.util.activity.getTimeSinceActive")||g.mf;g.m("yt.util.activity.getTimeSinceActive",eca,void 0);var fca=g.p("yt.util.activity.setTimestamp")||kf;g.m("yt.util.activity.setTimestamp",fca,void 0);var Hg,Mg;g.Lg=null;Mg="";g.Ng.prototype.stopPropagation=function(){this.Zf=!0};
g.Ng.prototype.preventDefault=function(){this.defaultPrevented=!0;this.hv=!1};var dh,hca;g.gca=!g.F||g.Pc(9);dh=!g.F||g.Pc(9);hca=g.F&&!g.Nc("9");!g.Yc||g.Nc("528");g.Ef&&g.Nc("1.9b")||g.F&&g.Nc("8")||g.Ff&&g.Nc("9.5")||g.Yc&&g.Nc("528");g.Ef&&!g.Nc("8")||g.F&&g.Nc("9");g.t(g.Og,g.Ng);
g.Og.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?g.Ef&&(g.sa(e,"nodeName")||(e=null)):"mouseover"==c?e=a.fromElement:"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=g.Yc||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=g.Yc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?
a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pn=g.cg?a.metaKey:a.ctrlKey;this.state=a.state;this.ub=a;a.defaultPrevented&&this.preventDefault()};
g.Og.prototype.stopPropagation=function(){g.Og.L.stopPropagation.call(this);this.ub.stopPropagation?this.ub.stopPropagation():this.ub.cancelBubble=!0};
g.Og.prototype.preventDefault=function(){g.Og.L.preventDefault.call(this);var a=this.ub;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,hca)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
g.Og.prototype.Fq=g.ba(5);var Pg="closure_listenable_"+(1E6*Math.random()|0),lba=0;Sg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=Tg(e,b,c,d);return-1<b?(Rg(e[b]),g.Ma(e,b),0==e.length&&(delete this.A[a],this.C--),!0):!1};
Sg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,Rg(d[e]);delete this.A[c];this.C--}return b};var ah="closure_lm_"+(1E6*Math.random()|0),gh={},ch=0,jh="__closure_events_fn_"+(1E9*Math.random()>>>0);g.t(g.kh,g.qb);g.kh.prototype[Pg]=!0;g.h=g.kh.prototype;g.h.lj=function(){return this.so};
g.h.si=g.ba(6);g.h.addEventListener=function(a,b,c,d){g.Xg(this,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.eh(this,a,b,c,d)};
g.h.dispatchEvent=function(a){var b,c=this.lj();if(c){b=[];for(var d=1;c;c=c.lj())b.push(c),++d}c=this.qx;d=a.type||a;if(g.ka(a))a=new g.Ng(a,c);else if(a instanceof g.Ng)a.target=a.target||c;else{var e=a;a=new g.Ng(d,c);g.$a(a,e)}var e=!0,f;if(b)for(var k=b.length-1;!a.Zf&&0<=k;k--)f=a.currentTarget=b[k],e=lh(f,d,!0,a)&&e;a.Zf||(f=a.currentTarget=c,e=lh(f,d,!0,a)&&e,a.Zf||(e=lh(f,d,!1,a)&&e));if(b)for(k=0;!a.Zf&&k<b.length;k++)f=a.currentTarget=b[k],e=lh(f,d,!1,a)&&e;return e};
g.h.U=function(){g.kh.L.U.call(this);this.removeAllListeners();this.so=null};
g.h.O=function(a,b,c,d){return g.Ug(this.Y,String(a),b,!1,c,d)};
g.h.Va=function(a,b,c,d){return this.Y.remove(String(a),b,c,d)};
g.h.removeAllListeners=function(a){return this.Y?this.Y.removeAll(a):0};g.t(g.oh,g.qb);g.h=g.oh.prototype;g.h.tb=0;g.h.U=function(){g.oh.L.U.call(this);this.stop();delete this.A;delete this.C};
g.h.start=function(a){this.stop();this.tb=g.mh(this.Hc,g.ca(a)?a:this.B)};
g.h.stop=function(){this.isActive()&&g.nh(this.tb);this.tb=0};
g.h.isActive=function(){return 0!=this.tb};
g.h.Rl=function(){this.tb=0;this.A&&this.A.call(this.C)};var uh=[],vh=0,wh=0,sh=[],ph=0,th={},qh=new g.oh(vba,1E3);var yh=null,Bh=[];var Fh,Wh,Vh,Hh,Gh,Fba,yba,Bba,zba,Aba,Rh;Hh=0;Gh=0;Fba=["server_prefetched_vast","vmap"];yba=[900,60,"waiting"];Bba=[500,99,"waiting"];zba=[300,60,"waiting"];Aba=[400,99,"waiting"];Rh=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.xb,void 0);g.m("yt.pushConfigArray",function(a,b){var c=g.v(a,void 0);c?c.push(b):g.xb(a,[b])},void 0);
g.m("yt.getConfig",g.v,void 0);g.m("yt.hasMsg",g.Fb,void 0);g.m("yt.pubsub.publish",g.z,void 0);g.m("yt.pubsub.subscribe",g.x,void 0);g.m("yt.setMsg",function(a){vb(g.Eb,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){vb(g.Eb,arguments)},void 0);
g.m("ytcsi.tick",g.Ie,void 0);g.t(ai,g.Ub);
ai.prototype.enable=function(){window.onload=wba;window.onunload=xba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",Dh),window.addEventListener("spfhistory",Eh),window.addEventListener("spfrequest",Jh),window.addEventListener("spfpartprocess",Nh),window.addEventListener("spfpartdone",Oh),window.addEventListener("spfprocess",Ph),window.addEventListener("spfdone",Sh),window.addEventListener("spferror",Th),window.addEventListener("spfreload",
Uh),window.addEventListener("spfjsbeforeunload",bi)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",Dba),this.subscribe("dispose",Eba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
ai.prototype.init=function(){ai.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.v("PAGEFRAME_JS")?(b=g.v("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.p("ytbin.www.pageframe.setup")()}):a&&(a=g.p("yt.www.masthead.loadSearchbox"))&&a();
var a=g.v("JS_COMMON_MODULE"),d=g.v("JS_PAGE_MODULES");d||(d=[a]);a=g.v("JS_DELAY_LOAD",0);0<a?(g.Bb(this.B),this.B=g.zb(function(){b&&g.Dc(b,c);window.spf.script.require(d)},a)):(b&&g.Dc(b,c),window.spf.script.require(d));
kba();Saa();Naa();Ye(!0);g.He(!1);g.v("SERVICE_WORKER_KILLSWITCH",void 0)||"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.kd("service_worker_enabled")?Hba():window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(Iba))};
ai.prototype.dispose=function(){g.Bb(this.B);var a=g.p("ytbin.www.pageframe.cancelSetup");a&&a();g.Cb(Hg);if(a=g.Jg())a.removeEventListener("onReady",Ig),a.removeEventListener("onStateChange",Ig);Ye(!1);ai.L.dispose.call(this)};
ai.prototype.disable=function(){ai.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",Dh),window.removeEventListener("spfhistory",Eh),window.removeEventListener("spfrequest",Jh),window.removeEventListener("spfpartprocess",Nh),window.removeEventListener("spfpartdone",Oh),window.removeEventListener("spfprocess",Ph),window.removeEventListener("spfdone",Sh),window.removeEventListener("spferror",Th),window.removeEventListener("spfreload",Uh),window.removeEventListener("spfjsbeforeunload",
bi));window.onload=null;window.onunload=null;window.onerror=null};
g.Yb(new ai);})(_yt_www);
